### ISSUE TITLE
Support static

### ISSUE THREAD

**Issue by WanderG** [ffMathy/FluffySpoon.JavaScript.CSharpParser#10]
Classes with static methods or fields cause parsing errors.

Static methods are currently seen as having "static" as returntype

Static fields are seen as a method, and the method after it gets ignored.

**Comment by ffMathy** [comment]
Aha! I don't have much time at the moment but consider making a test for it and then make a PR. I'll gladly fix it!

**Comment by WanderG** [comment]
Thanks!

I have sent a PR that tests for static.
I also added 2 other tests for issues I ran into (constructors were always private and fields with an initial value messed up the parsing), I hope you don't mind.

I looked into fixing it myself, but don't have a proper grasp on how the parsing is currently done.

I'm using this library to generate documentation for an API that another team built, I don't normally work with C#

**Comment by ffMathy** [comment]
Thank you so much! I have merged it so the tests will now fail. Like I said I won't have much time, but it may arrive at around August.

Feel free to try in the meanwhile. You just need to look at the ClassParser.ts file.

**Comment by WanderG** [comment]
Submitted a PR

That actually went better than I expected, your regex helper is very tidy.

**Comment by ffMathy** [comment]
Perfect, and do all tests pass?

**Comment by WanderG** [comment]
Yes, npm run test reports no issues

**Comment by ffMathy** [comment]
It should now be deployed to npm. Thank you for your contributions!
